import logo from './logo.svg';
import './App.css';
import React from 'react';

class App extends React.Component {

  constructor(){
    super();
    this.state = {
      data:
      [
         {
            "tpl":1100,
            "insurance_type":"comprehensive",
            "premium":4516,
            "provider":{
               "en-ae":{
                  "url_slug":"watania",
                  "terms_conditions_url":"https:\/\/bnkn.us\/insurance-terms\/WataniaTerms.pdf",
                  "image_url":"https:\/\/static4.bnkn.us.com\/ci\/providers\/watania.png",
                  "name":"Watania",
                  "description":"National Takaful Company (Watania) is a young and dynamic organization that came into being in 2011. Watania\u2019s General Takaful department is responsible for all classes of insurance other than Motor and Medical. Resourced with highly experienced staff, this department is dedicated to serve mainly the commercial insurance needs of the market. The department has developed a wide a range of products to cater to the requirement of business of all sizes and types in all the major sectors of the market. All the products are Shariah compliant.",
                  "time_to_policy":1,
                  "product_name":"Watania Premium (Garage)"
               }
            },
            "excess":1000,
            "currency":"AED",
            "id":"wataniapremium",
            "price_breakdown":{
               "modifiers":[
                  {
                     "terms":{
                        "starts_at":"2017-01-01T00:00:00.000+0000",
                        "product":"ALL",
                        "code":"",
                        "name":"Ramadan extended",
                        "ends_at":"2017-12-12T00:00:00.000+0000",
                        "type":"discountPercentage",
                        "value":"0.06"
                     },
                     "category":"voucher"
                  }
               ],
               "base":4805
            },
            "covers":[
               {
                  "name":"personalAccidentForDriver",
                  "options":[
                     {
                        "cost":120
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"dentRepair",
                  "type":"excluded"
               },
               {
                  "name":"replacementLocksCovered",
                  "type":"excluded"
               },
               {
                  "name":"thirdPartyPropertyDamage",
                  "options":[
                     {
                        "text":"Up to AED 2M"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"omanExtension",
                  "options":[
                     {
                        "cost":1000
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"lossOrDamageToVehicleCovered",
                  "type":"included"
               },
               {
                  "name":"valetParkingTheftCover",
                  "type":"excluded"
               },
               {
                  "name":"thirdPartyBodilyInjuryCovered",
                  "options":[
                     {
                        "text":"Unlimited"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"agencyRepair",
                  "type":"excluded"
               },
               {
                  "name":"lossOfPersonalEffects",
                  "type":"excluded"
               },
               {
                  "name":"emergencyMedicalExpenses",
                  "options":[
                     {
                        "text":"Up to AED 2,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"personalAccidentForPassenger",
                  "options":[
                     {
                        "cost":150
                     },
                     {
                        "text":"Family and Friends included"
                     }
                  ],
                  "type":"excluded",
                  "selected":false
               },
               {
                  "name":"ambulanceFees",
                  "type":"included"
               },
               {
                  "name":"naturalCalamityCovered",
                  "type":"excluded"
               },
               {
                  "name":"autoGapInsurance",
                  "type":"excluded"
               },
               {
                  "name":"riotOrStrikesCovered",
                  "type":"excluded"
               },
               {
                  "name":"gccCovered",
                  "type":"excluded"
               },
               {
                  "name":"involuntaryEmploymentLoss",
                  "type":"excluded"
               },
               {
                  "name":"carRental",
                  "options":[
                     {
                        "cost":200
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"windScreenDamage",
                  "options":[
                     {
                        "text":"Up to AED 3,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"noExcessForWindscreenDamage",
                  "type":"included"
               },
               {
                  "name":"roadsideAssistance",
                  "type":"included"
               },
               {
                  "name":"fireAndTheftCovered",
                  "type":"included"
               },
               {
                  "name":"protectedNoClaimsDiscount",
                  "type":"excluded"
               },
               {
                  "name":"offroadCovered",
                  "type":"excluded"
               },
               {
                  "name":"freeCarRegistrationService",
                  "type":"included"
               }
            ],
            "own_damage":3705
         },
         {
            "tpl":1100,
            "insurance_type":"comprehensive",
            "premium":5943,
            "provider":{
               "en-ae":{
                  "url_slug":"watania",
                  "terms_conditions_url":"https:\/\/static4.bnkn.us\/insurance-terms\/WataniaTerms.pdf",
                  "image_url":"https:\/\/static4.bnkn.us\/ci\/providers\/watania.png",
                  "name":"Watania",
                  "description":"National Takaful Company (Watania) is a young and dynamic organization that came into being in 2011. Watania\u2019s General Takaful department is responsible for all classes of insurance other than Motor and Medical. Resourced with highly experienced staff, this department is dedicated to serve mainly the commercial insurance needs of the market. The department has developed a wide a range of products to cater to the requirement of business of all sizes and types in all the major sectors of the market. All the products are Shariah compliant.",
                  "time_to_policy":1,
                  "product_name":"Watania Agency"
               }
            },
            "excess":1000,
            "currency":"AED",
            "id":"wataniaagency",
            "price_breakdown":{
               "modifiers":[
                  {
                     "terms":{
                        "starts_at":"2017-01-01T00:00:00.000+0000",
                        "product":"ALL",
                        "code":"",
                        "name":"Ramadan extended",
                        "ends_at":"2017-12-12T00:00:00.000+0000",
                        "type":"discountPercentage",
                        "value":"0.06"
                     },
                     "category":"voucher"
                  }
               ],
               "base":6322
            },
            "covers":[
               {
                  "name":"personalAccidentForDriver",
                  "options":[
                     {
                        "cost":120
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"dentRepair",
                  "type":"excluded"
               },
               {
                  "name":"replacementLocksCovered",
                  "type":"excluded"
               },
               {
                  "name":"thirdPartyPropertyDamage",
                  "options":[
                     {
                        "text":"Up to AED 2M"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"omanExtension",
                  "options":[
                     {
                        "cost":1000
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"lossOrDamageToVehicleCovered",
                  "type":"included"
               },
               {
                  "name":"valetParkingTheftCover",
                  "type":"excluded"
               },
               {
                  "name":"thirdPartyBodilyInjuryCovered",
                  "options":[
                     {
                        "text":"Unlimited"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"agencyRepair",
                  "type":"included"
               },
               {
                  "name":"lossOfPersonalEffects",
                  "type":"excluded"
               },
               {
                  "name":"emergencyMedicalExpenses",
                  "options":[
                     {
                        "text":"Up to AED 2,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"personalAccidentForPassenger",
                  "options":[
                     {
                        "cost":150
                     },
                     {
                        "text":"Family and Friends included"
                     }
                  ],
                  "type":"excluded",
                  "selected":false
               },
               {
                  "name":"ambulanceFees",
                  "type":"included"
               },
               {
                  "name":"naturalCalamityCovered",
                  "type":"excluded"
               },
               {
                  "name":"autoGapInsurance",
                  "type":"included"
               },
               {
                  "name":"riotOrStrikesCovered",
                  "type":"excluded"
               },
               {
                  "name":"gccCovered",
                  "type":"excluded"
               },
               {
                  "name":"involuntaryEmploymentLoss",
                  "type":"excluded"
               },
               {
                  "name":"carRental",
                  "options":[
                     {
                        "cost":200
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"windScreenDamage",
                  "options":[
                     {
                        "text":"Up to AED 3,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"noExcessForWindscreenDamage",
                  "type":"included"
               },
               {
                  "name":"roadsideAssistance",
                  "type":"included"
               },
               {
                  "name":"fireAndTheftCovered",
                  "type":"included"
               },
               {
                  "name":"protectedNoClaimsDiscount",
                  "type":"excluded"
               },
               {
                  "name":"offroadCovered",
                  "type":"excluded"
               },
               {
                  "name":"freeCarRegistrationService",
                  "type":"included"
               }
            ],
            "own_damage":5222
         },
         {
            "tpl":1100,
            "insurance_type":"comprehensive",
            "premium":3506,
            "provider":{
               "en-ae":{
                  "url_slug":"watania",
                  "terms_conditions_url":"https:\/\/static4.bnkn.us\/insurance-terms\/WataniaTerms.pdf",
                  "image_url":"https:\/\/static4.bnkn.us\/ci\/providers\/watania.png",
                  "name":"Watania",
                  "description":"National Takaful Company (Watania) is a young and dynamic organization that came into being in 2011. Watania\u2019s General Takaful department is responsible for all classes of insurance other than Motor and Medical. Resourced with highly experienced staff, this department is dedicated to serve mainly the commercial insurance needs of the market. The department has developed a wide a range of products to cater to the requirement of business of all sizes and types in all the major sectors of the market. All the products are Shariah compliant.",
                  "time_to_policy":1,
                  "product_name":"Watania Garage"
               }
            },
            "excess":1000,
            "currency":"AED",
            "id":"wataniagarage",
            "price_breakdown":{
               "modifiers":[
                  {
                     "terms":{
                        "starts_at":"2017-01-01T00:00:00.000+0000",
                        "product":"ALL",
                        "code":"",
                        "name":"Ramadan extended",
                        "ends_at":"2017-12-12T00:00:00.000+0000",
                        "type":"discountPercentage",
                        "value":"0.06"
                     },
                     "category":"voucher"
                  }
               ],
               "base":3730
            },
            "covers":[
               {
                  "name":"personalAccidentForDriver",
                  "options":[
                     {
                        "cost":120
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"dentRepair",
                  "type":"excluded"
               },
               {
                  "name":"replacementLocksCovered",
                  "type":"excluded"
               },
               {
                  "name":"thirdPartyPropertyDamage",
                  "options":[
                     {
                        "text":"Up to AED 2M"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"omanExtension",
                  "options":[
                     {
                        "cost":1000
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"lossOrDamageToVehicleCovered",
                  "type":"included"
               },
               {
                  "name":"valetParkingTheftCover",
                  "type":"excluded"
               },
               {
                  "name":"thirdPartyBodilyInjuryCovered",
                  "options":[
                     {
                        "text":"Unlimited"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"agencyRepair",
                  "type":"excluded"
               },
               {
                  "name":"lossOfPersonalEffects",
                  "type":"excluded"
               },
               {
                  "name":"emergencyMedicalExpenses",
                  "options":[
                     {
                        "text":"Up to AED 2,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"personalAccidentForPassenger",
                  "options":[
                     {
                        "cost":150
                     },
                     {
                        "text":"Family and Friends included"
                     }
                  ],
                  "type":"excluded",
                  "selected":false
               },
               {
                  "name":"ambulanceFees",
                  "type":"included"
               },
               {
                  "name":"naturalCalamityCovered",
                  "type":"excluded"
               },
               {
                  "name":"autoGapInsurance",
                  "type":"excluded"
               },
               {
                  "name":"riotOrStrikesCovered",
                  "type":"excluded"
               },
               {
                  "name":"gccCovered",
                  "type":"excluded"
               },
               {
                  "name":"involuntaryEmploymentLoss",
                  "type":"excluded"
               },
               {
                  "name":"carRental",
                  "options":[
                     {
                        "cost":200
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"windScreenDamage",
                  "options":[
                     {
                        "text":"Up to AED 3,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"noExcessForWindscreenDamage",
                  "type":"included"
               },
               {
                  "name":"roadsideAssistance",
                  "type":"included"
               },
               {
                  "name":"fireAndTheftCovered",
                  "type":"included"
               },
               {
                  "name":"protectedNoClaimsDiscount",
                  "type":"excluded"
               },
               {
                  "name":"offroadCovered",
                  "type":"excluded"
               },
               {
                  "name":"freeCarRegistrationService",
                  "type":"included"
               }
            ],
            "own_damage":2630
         },
         {
            "insurance_type":"comprehensive",
            "premium":3566,
            "provider":{
               "en-ae":{
                  "url_slug":"union",
                  "terms_conditions_url":"https:\/\/static4.bnkn.us\/insurance-terms\/UnionTerms.pdf",
                  "image_url":"https:\/\/static4.bnkn.us\/ci\/providers\/union-logo_19072017.png",
                  "name":"Union",
                  "description":"Established in 1998 and listed on the Abu Dhabi Securities Exchange, Union Insurance Company provides a wide range of individual and commercial insurance products to clients in the UAE and Middle East region. This includes both standard and customised policies that help individuals, small, medium and large enterprises as well as government entities obtain reliable, cost-effective insurance cover.",
                  "time_to_policy":24,
                  "product_name":"Union Silver"
               }
            },
            "excess":1000,
            "currency":"AED",
            "id":"unionsilver",
            "price_breakdown":{
               "modifiers":[
                  {
                     "terms":{
                        "starts_at":"2017-01-01T00:00:00.000+0000",
                        "product":"ALL",
                        "code":"",
                        "name":"Ramadan extended",
                        "ends_at":"2017-12-12T00:00:00.000+0000",
                        "type":"discountPercentage",
                        "value":"0.06"
                     },
                     "category":"voucher"
                  }
               ],
               "base":3793
            },
            "covers":[
               {
                  "name":"personalAccidentForDriver",
                  "options":[
                     {
                        "cost":120
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"dentRepair",
                  "type":"excluded"
               },
               {
                  "name":"replacementLocksCovered",
                  "type":"excluded"
               },
               {
                  "name":"agencyRepair",
                  "options":[
                     {
                        "cost":506
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"thirdPartyPropertyDamage",
                  "options":[
                     {
                        "text":"Up to AED 2M"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"lossOrDamageToVehicleCovered",
                  "type":"included"
               },
               {
                  "name":"valetParkingTheftCover",
                  "type":"excluded"
               },
               {
                  "name":"thirdPartyBodilyInjuryCovered",
                  "options":[
                     {
                        "text":"Unlimited"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"lossOfPersonalEffects",
                  "type":"excluded"
               },
               {
                  "name":"omanExtension",
                  "type":"excluded"
               },
               {
                  "name":"involuntaryEmploymentLoss",
                  "options":[
                     {
                        "text":"Up to AED 5,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"ambulanceFees",
                  "type":"included"
               },
               {
                  "name":"naturalCalamityCovered",
                  "type":"included"
               },
               {
                  "name":"autoGapInsurance",
                  "type":"included"
               },
               {
                  "name":"riotOrStrikesCovered",
                  "type":"included"
               },
               {
                  "name":"gccCovered",
                  "type":"included"
               },
               {
                  "name":"carRental",
                  "options":[
                     {
                        "cost":175
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"windScreenDamage",
                  "type":"excluded"
               },
               {
                  "name":"personalAccidentForPassenger",
                  "options":[
                     {
                        "text":"Family Only"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"noExcessForWindscreenDamage",
                  "type":"excluded"
               },
               {
                  "name":"roadsideAssistance",
                  "type":"included"
               },
               {
                  "name":"fireAndTheftCovered",
                  "type":"included"
               },
               {
                  "name":"protectedNoClaimsDiscount",
                  "type":"included"
               },
               {
                  "name":"offroadCovered",
                  "type":"excluded"
               },
               {
                  "name":"emergencyMedicalExpenses",
                  "type":"excluded"
               },
               {
                  "name":"freeCarRegistrationService",
                  "type":"excluded"
               }
            ]
         },
         {
            "insurance_type":"comprehensive",
            "premium":3744,
            "provider":{
               "en-ae":{
                  "url_slug":"union",
                  "terms_conditions_url":"https:\/\/static4.bnkn.us\/insurance-terms\/UnionTerms.pdf",
                  "image_url":"https:\/\/static4.bnkn.us\/ci\/providers\/union-logo_19072017.png",
                  "name":"Union",
                  "description":"Established in 1998 and listed on the Abu Dhabi Securities Exchange, Union Insurance Company provides a wide range of individual and commercial insurance products to clients in the UAE and Middle East region. This includes both standard and customised policies that help individuals, small, medium and large enterprises as well as government entities obtain reliable, cost-effective insurance cover.",
                  "time_to_policy":24,
                  "product_name":"Union Gold"
               }
            },
            "excess":1000,
            "currency":"AED",
            "id":"uniongold",
            "price_breakdown":{
               "modifiers":[
                  {
                     "terms":{
                        "starts_at":"2017-01-01T00:00:00.000+0000",
                        "product":"ALL",
                        "code":"",
                        "name":"Ramadan extended",
                        "ends_at":"2017-12-12T00:00:00.000+0000",
                        "type":"discountPercentage",
                        "value":"0.06"
                     },
                     "category":"voucher"
                  }
               ],
               "base":3983
            },
            "covers":[
               {
                  "name":"personalAccidentForDriver",
                  "options":[
                     {
                        "cost":120
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"gccCovered",
                  "options":[
                     {
                        "text":"Oman and Qatar Only"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"dentRepair",
                  "type":"included"
               },
               {
                  "name":"replacementLocksCovered",
                  "options":[
                     {
                        "text":"Up to AED 1,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"agencyRepair",
                  "options":[
                     {
                        "cost":443
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"thirdPartyPropertyDamage",
                  "options":[
                     {
                        "text":"Up to AED 5M"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"lossOrDamageToVehicleCovered",
                  "type":"included"
               },
               {
                  "name":"valetParkingTheftCover",
                  "type":"included"
               },
               {
                  "name":"thirdPartyBodilyInjuryCovered",
                  "options":[
                     {
                        "text":"Unlimited"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"lossOfPersonalEffects",
                  "options":[
                     {
                        "text":"Up to AED 5,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"emergencyMedicalExpenses",
                  "options":[
                     {
                        "text":"Up to AED 6,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"omanExtension",
                  "type":"included"
               },
               {
                  "name":"involuntaryEmploymentLoss",
                  "options":[
                     {
                        "text":"Up to AED 5,000"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"ambulanceFees",
                  "type":"included"
               },
               {
                  "name":"naturalCalamityCovered",
                  "type":"included"
               },
               {
                  "name":"autoGapInsurance",
                  "type":"included"
               },
               {
                  "name":"riotOrStrikesCovered",
                  "type":"included"
               },
               {
                  "name":"carRental",
                  "options":[
                     {
                        "cost":175
                     }
                  ],
                  "type":"optional",
                  "selected":false
               },
               {
                  "name":"windScreenDamage",
                  "type":"included"
               },
               {
                  "name":"personalAccidentForPassenger",
                  "options":[
                     {
                        "text":"Family Only"
                     }
                  ],
                  "type":"included"
               },
               {
                  "name":"noExcessForWindscreenDamage",
                  "type":"included"
               },
               {
                  "name":"roadsideAssistance",
                  "type":"included"
               },
               {
                  "name":"fireAndTheftCovered",
                  "type":"included"
               },
               {
                  "name":"protectedNoClaimsDiscount",
                  "type":"included"
               },
               {
                  "name":"offroadCovered",
                  "type":"excluded"
               },
               {
                  "name":"freeCarRegistrationService",
                  "type":"included"
               }
            ]
         }
      ],
      searchTerm: '',
      sortValue:null,
      type:""
    }
    this.searchTerm = this.search.bind(this);
  }
  
  search(e) {
    this.setState({ searchTerm: e.target.value });
  }
  sortFunction(sortValue,typeofSort, event) {
    this.setState({sortValue: sortValue,type:typeofSort});
    console.log(this.state);
  }
  render() {
    return(
    <div className="App">
      <header>
        <h1>First React Project </h1>
      </header>
      <input
          class="search-box"
          placeholder="search by insurance type or provider"
          onKeyUp={e => this.searchTerm(e)}
          type="text"
        />
        <div>
          <button value="hightolow" onClick={this.sortFunction.bind(this,'premium','lowtohigh')}>Low to High</button>
          <button value="hightolow" onClick={this.sortFunction.bind(this,'premium','hightolow')}>High to Low </button>
        </div>
        <div>
        <ul class="collapse-able">
          {this.state.data
            .filter(user => {
              console.log(user)
              return (
                user.insurance_type.toLowerCase().indexOf(this.state.searchTerm.toLowerCase()) > -1 ||
                user.provider['en-ae']?.name?.toLowerCase().indexOf(this.state.searchTerm.toLowerCase())>-1
              );
            }).sort((a,b)=>{
              let aVal = a[this.state.sortValue];
              let  bVal = b[this.state.sortValue];
              console.log(this.state.type)
              if(this.state.type ==="lowtohigh")
              {
                
                return aVal - bVal;
              }

              if(this.state.type==="hightolow")
              {
                
                return bVal-aVal;
              }
            })
            .map((user,i)=> {
              return (
                <li key={i}>
                  <h2>Insurance Type : {user.insurance_type}</h2>
                    <div>          
                      <p>Premium : {user.premium}</p>
                      <p>{user.provider['en-ae']?.name}</p>
                    </div>
                </li>
              );
            })}
            </ul>
      </div>
      </div>
      )
  }
}


export default App;